# Generated by Django 3.1.5 on 2021-02-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memberTbl',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
                ('birthdate', models.DateTimeField(verbose_name='date published')),
                ('mobile', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='videoTbl',
            fields=[
                ('ID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('video_url', models.CharField(max_length=64)),
                ('image_url', models.CharField(max_length=64)),
                ('upload_time', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='playlistTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.membertbl')),
                ('videoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.videotbl')),
            ],
        ),
        migrations.CreateModel(
            name='historyTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.membertbl')),
                ('videoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.videotbl')),
            ],
        ),
    ]
