# Generated by Django 3.1.5 on 2021-02-22 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytbl',
            name='play_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videotbl',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
